// Generated by CoffeeScript 1.9.0
var Planet,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

Planet = (function(_super) {
  __extends(Planet, _super);

  function Planet(name, radius, distanceFromOrigin, img, glowColorS, speed) {
    var geometry, glowColor, material, texture;
    this.mesh = new THREE.Object3D();
    geometry = new THREE.SphereGeometry(radius, 32, 32);
    texture = THREE.ImageUtils.loadTexture(THREEx.Planets.baseURL + ("images/" + img + ".jpg"));
    material = new THREE.MeshPhongMaterial({
      map: texture,
      bumpMap: texture,
      bumpScale: 0.05
    });
    this.planet = new THREE.Mesh(geometry, material);
    this.planet.position.x = distanceFromOrigin;
    this.mesh.add(this.planet);
    glowColor = new THREE.Color(glowColorS);
    geometry = new THREE.SphereGeometry(radius, 32, 32);
    geometry = this.planet.geometry.clone();
    material = THREEx.createAtmosphereMaterial();
    material.uniforms.glowColor.value = glowColor;
    this.glow = new THREE.Mesh(geometry, material);
    this.glow.scale.multiplyScalar(1.05);
    this.planet.add(this.glow);
    this.clouds = THREEx.Planets.createEarthCloud();
    this.clouds.geometry = new THREE.SphereGeometry(radius + 0.1, 32, 32);
    this.planet.add(this.clouds);
    this.ring = THREEx.Planets.createSaturnRing();
    this.ring.geometry = new THREEx.Planets._RingGeometry(1.55 * radius, 1.75 * radius, 64);
    this.planet.add(this.ring);
    this.speed = speed;
  }

  Planet.prototype.setDateRotation = function(time) {
    return this.mesh.rotation.y = time * this.speed / 100;
  };

  Planet.prototype.animateClouds = function(tpf) {
    return this.clouds.rotation.y += 1 / 8 * tpf;
  };

  return Planet;

})(BaseModel);
